[tools]
# TypeScript
pnpm = "latest"
"npm:@vtsls/language-server" = "latest"

# Haskell
ghcup = "0.1.50.2"

# Lua
lua-language-server = "latest"

# Python
uv = "latest"

# Rust
rust-analyzer = "latest"

# Go
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"

# Zig
zls = "latest"

# Markdown
marksman = "latest"

# bash
"npm:bash-language-server" = "latest"

# HTML, CSS JSON, ESLint
"npm:vscode-langservers-extracted" = "latest"

# yaml
"npm:yaml-language-server" = "latest"
