[tools]
"npm:oxfmt" = "latest"
act = "latest"
bottom = "latest"
dust = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
glow = "latest"
lazygit = "latest"
neovim = "latest"
starship = "latest"
task = "latest"
yt-dlp = "latest"
zoxide = "latest"
